import { Inter } from "next/font/google"
import "./globals.css"
import StoreProvider from "./StoreProvider"
import Navbar from "./components/navbar"
import Footer from "./components/footer"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="min-h-screen">
      <body
        className={`${inter.className} + min-h-screen flex flex-col justify-between`}
      >
        <StoreProvider>
          <div className="w-full flex flex-col justify-center items-center">
            <header className="w-full">
              <Navbar />
            </header>
            <main className="w-7xl h-full mt-4">{children}</main>
          </div>
          <Footer />
        </StoreProvider>
      </body>
    </html>
  )
}
